// users.js
window.PM_USERS = [
  { user: "MUÑOZRAUL", pass: "MUÑRAU1918" },
  { user: "RODRIGUEZJORGE", pass: "RODJOR1887" },
  { user: "DIAZSEBASTIAN", pass: "DIASEB1896" },
  { user: "RODRIGUEZGUILLERMO", pass: "RODGUI1001205" },
  { user: "ROBLESGONZALEZJOVAN", pass: "ROBJOV3102" },
  { user: "CRUZDARIO", pass: "CRUDAR1903" },
  { user: "MANOLUCOSMARIEL", pass: "MANMAR1003166" },
  { user: "VERAVICTOR", pass: "VERVIC1919" },
  { user: "BIANISLUIS", pass: "BIALUI2131" },
  { user: "BARRERACARLOS", pass: "BARCAR2514" },
  { user: "BASTIASJOSE", pass: "BASJOS1194" },
  { user: "VALLEJOSCARLOS", pass: "VALCAR10194" },
  { user: "LUNAESTEBAN", pass: "LUNEST2648" },
  { user: "MONTESDIEGO", pass: "MONDIE2014" },
  { user: "ALEGREDAVID", pass: "ALEDAV1893" },
  { user: "ESCOBARANIBAL", pass: "ESCANI1890" },
  { user: "SOSACLAUDIO", pass: "SOSCLA3198" },
  { user: "CURRYMAURICIO", pass: "CURMAU1892" },
  { user: "INAIPILMAXIMILIANO", pass: "INAMAX3058" },
  { user: "BLANCOTOMAS", pass: "BLATOM1002865" },
  { user: "SAUXRODRIGO", pass: "SAUROD1899" },
  { user: "URIBEPABLO", pass: "URIPAB1944" },
  { user: "FERNANDEZFRANCO", pass: "FERFRA3249" },
  { user: "REYESCARLOS", pass: "REYCAR2104" },
  { user: "PERFORADORASMANTENIMIENTO", pass: "PERMAN2026" },
  { user: "ARGUELLOLUCAS", pass: "ARGLUC3083" },
  { user: "BENICIOCRISTIAN", pass: "BENCRI2796" },
  { user: "COLQUEARMANDO", pass: "COLARM938" },
  { user: "CARRIZOENZO", pass: "CarEnz1891" }
];
